### ISSUE TITLE
4-20mA failing in tests

### ISSUE THREAD

**Issue by MiguelASTavares** [SequentMicrosystems/megaind-rpi#17]
Hi, I acquired two of these hats. I was testing the 4-20mA inputs and in one of the hats, all four channels are returning a value of 65mA. The other has 3 channels at 0 mA and one at 65mA. This makes the hats fail in the provided test scripts since the values are out of range. Is there something I'm doing wrong since all the incorrect values are similar? I really appreciate any help in this situation. 

Thanks.
Miguel Tavares.

**Comment by alexburcea2877** [comment]
Hi, 
The firmware version 2.01 has been released and fixed the problem. Please follow the instruction from https://github.com/SequentMicrosystems/megaind-rpi/tree/master/update to update the card firmware version. Let me know the results.

Regards,
Alex.

**Comment by MiguelASTavares** [comment]
Hi, after the firmware update all channels are returning 0.0 (or close to), so I think it's solved. Can you explain what the problem was?

**Comment by alexburcea2877** [comment]
The problem was simple, The firmware calculate the value as a floating point number including calibration in 2 points. If the offset calibrated during position has changed a little, the values become negative.
The I2C transaction between the card and the rpi is made as 16bits unsigned integer scaled to microamperes  and  65mA means 65000 microampere which actually is a small negative number.

**Comment by MiguelASTavares** [comment]
Ok, once again thanks for the fast response, everything is working fine now. 

Miguel Tavares.
